Added H2 with Resources
ably/ably-go pull request #285
Opened 2021-02-23 17:07 UTC by ramiro-nd

Added resources with links to our Go content.

2021-02-24 14:22 UTC, mattheworiordan approved these changes
On balance I think we need to be very careful about polluting our documentation with marketing content, but I think this content is relevant to the audience.

However, I think "Resources" is maybe not the right title as it implies (to me) that these are resources relating to the SDK itself.

BTW. I would put this above https://github.com/ably/ably-go#release-process, given the release process is aimed at devs building SDKs, whereas this is for consumers of the SDK.  You could move Support & feedback up too given that is the case.

2021-03-11 15:47 UTC, QuintinWillison commented
Sorry, I've only just passed by and seen Matt's comment here.

I'll add @tbedford as a reviewer as he has told me that he is planning to work on conforming read me documents.

In @ramiro-nd's defence, the "Resources" title does match what we currently have [in Flutter](https://github.com/ably/ably-flutter#resources). 😁 

Also, one of the tasks in the SDK Team's backlog is to move client library developer focussed read me content to a discrete `CONTRIBUTING` file - as we have already done [in ably-js](https://github.com/ably/ably-js#contributing).

2021-03-11 17:05 UTC, tbedford reviewed
A few comments:

* Instead of Resources you could go with "Further information". It depends a bit on what you're linking to as to the best option. I'd probably go with the latter, but not a blocker.
* You could also add a line of text before the bullet points describing the nature of the resources and why someone should be interested in them.
* Shouldn't we be using `ably.com`? I'm confused about this - we changed a lot of links in docs to point at `ably.com`.

2021-03-12 09:32 UTC, ramiro-nd commented
@tbedford I actually created the PR just before the migration to .com, but you are right. I updated those and all the links to ably.com. Tedious thing to do but we should do it in every repo.

Let me know if it's good to go now.

2021-03-12 09:39 UTC, QuintinWillison requested changes
Thanks for making the unrelated changes to update `ably.io` references to `ably.com`. We're going to get that done in other repositories very soon.

2021-03-12 09:39 UTC, QuintinWillison commented on README.md
> +[contact Ably customer support](http://knowledge.ably.com/). Pull Requests are also welcomed.
Should be using `https`.

2021-03-12 09:39 UTC, QuintinWillison commented on README.md
> +Please visit http://knowledge.ably.com/ for access to our knowledgebase and to ask for any assistance.
Should be using `https`.

2021-03-15 08:17 UTC, tbedford approved these changes

2021-05-06 14:27 UTC, merged