Channel message dispatch only when it's attached
ably/ably-go pull request #294
Opened 2021-03-09 19:18 UTC by sacOO7

- Added missing channel attached check
- Updated tests for the same
- Fixes #240

2021-03-20 08:03 UTC, tcard approved these changes

2021-03-20 08:08 UTC, tcard requested changes

2021-03-20 08:08 UTC, tcard commented on ably/realtime_channel.go
> +		if c.state == ChannelStateAttached {
This access to `c.state` should happen while holding a lock on `c.mtx`. (This really should be easier to deal with; see #184.)

```suggestion
		c.mtx.Lock()
		state := c.state
		c.mtx.Unlock()
		if state == ChannelStateAttached {
```

2021-03-23 07:34 UTC, tcard commented
It looks like there's a test that's consistently failing:

```
=== CONT  TestRealtimeChannel_Detach
    realtime_channel_test.go:151: waiting on subscribed channel close timed out after 30s
```

2021-03-23 15:48 UTC, sacOO7 commented
> It looks like there's a test that's consistently failing:
> 
> ```
> === CONT  TestRealtimeChannel_Detach
>     realtime_channel_test.go:151: waiting on subscribed channel close timed out after 30s
> ```

Yeah, seems it's flaky, I am not sure if there is a way to fix it.

2021-04-06 08:34 UTC, lmars approved these changes

2021-04-25 18:47 UTC, lmars commented
@sacOO7 is there anything remaining to be done on this PR?

2021-05-06 14:28 UTC, merged