feat: retry on cloudfront http errors
ably/ably-go pull request #572
Opened 2022-12-12 12:14 UTC by owenpearson

Resolves #571

2022-12-13 16:00 UTC, stmoreau approved these changes

2022-12-13 18:41 UTC, sacOO7 commented on ably/rest_client.go
>  }
Code can be updated to 
```golang
func canFallBack(statusCode int, header http.Header) bool {
  return (http.StatusInternalServerError <= statusCode && statusCode <= http.StatusGatewayTimeout) ||
  (header.Get("Server") == "Cloudfront" &&  statusCode >= http.StatusBadRequest) // RSC15l4
}
```
This is easy to read as per the spec

2022-12-13 19:04 UTC, sacOO7 commented
@owenpearson it seems some of the tests are failing : (

2022-12-14 21:35 UTC, sacOO7 commented on ably/rest_client.go
>  }
Code has been updated as per requirement.

2022-12-15 13:21 UTC, QuintinWillison requested changes

2022-12-15 13:25 UTC, sacOO7 commented on ably/rest_client.go
> +		(res != nil && res.Header.Get("Server") == "Cloudfront" && statusCode >= http.StatusBadRequest) // RSC15l4
Thanks for pointing, I will update 👍

2022-12-15 13:29 UTC, SimonWoolf commented on ably/rest_client.go
> +		(res != nil && res.Header.Get("Server") == "Cloudfront" && statusCode >= http.StatusBadRequest) // RSC15l4
It is indeed `CloudFront`, you can try it yourself with netcat
![cf](https://user-images.githubusercontent.com/5908687/207871228-48eab42f-22a0-4987-bb7c-d2f31eccddca.png)

I agree a case-insensitive comparison is safer though.

2022-12-15 13:29 UTC, sacOO7 commented on ably/rest_client.go
> +		(res != nil && res.Header.Get("Server") == "Cloudfront" && statusCode >= http.StatusBadRequest) // RSC15l4
Made string compare case-insensitive as per https://www.educative.io/answers/what-is-the-equalfold-function-in-golang

2022-12-15 13:34 UTC, SimonWoolf approved these changes

2022-12-15 14:08 UTC, QuintinWillison approved these changes

2022-12-15 15:07 UTC, lmars approved these changes

2022-12-15 15:25 UTC, sacOO7 approved these changes

2022-12-16 09:05 UTC, merged